name: Deploy to GitHub Pages
on:
  push:
    branches: [main]          # change if you use a different default branch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # EXAMPLE: Flutter — swap for npm / pnpm / yarn etc.
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build web --release

      # Publish the build folder to the gh-pages branch
      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web          # adjust to your build output